import type { App } from 'vue'
import { BaseForm } from './BaseForm'
import {
  BetaSchemaForm,
  ProFormCaptcha,
  ProFormCascader,
  ProFormCheckbox,
  ProFormCheckboxGroup,
  ProFormColorPicker,
  ProFormDateMonthRangePicker,
  ProFormDatePicker,
  ProFormDateQuarterRangePicker,
  ProFormDateRangePicker,
  ProFormDateTimePicker,
  ProFormDateTimeRangePicker,
  ProFormDateWeekRangePicker,
  ProFormDateYearRangePicker,
  ProFormDependency,
  ProFormDigit,
  ProFormDigitRange,
  ProFormField,
  ProFormFieldSet,
  ProFormGroup,
  ProFormItem,
  ProFormList,
  ProFormMoney,
  ProFormRadio,
  ProFormRadioButton,
  ProFormRadioGroup,
  ProFormRate,
  ProFormSegmented,
  ProFormSelect,
  ProFormSlider,
  ProFormSwitch,
  ProFormText,
  ProFormTextArea,
  ProFormTextPassword,
  ProFormTimePicker,
  ProFormTimeRangePicker,
  ProFormTreeSelect,
  ProFormUploadButton,
  ProFormUploadDragger,
} from './components'
import { MyFormItem } from './form-item.tsx'
import Form from './form.vue'
import {
  DrawerForm,
  FieldLabel,
  FilterDropdown,
  LightFilter,
  LightFilterCascader,
  LightFilterCheckboxGroup,
  LightFilterDate,
  LightFilterDateRange,
  LightFilterDateTime,
  LightFilterDateTimeRange,
  LightFilterDigit,
  LightFilterDigitRange,
  LightFilterFieldSet,
  LightFilterInput,
  LightFilterMonthRange,
  LightFilterPassword,
  LightFilterQuarterRange,
  LightFilterSearchSelect,
  LightFilterSelect,
  LightFilterSlider,
  LightFilterSwitch,
  LightFilterText,
  LightFilterTextArea,
  LightFilterTime,
  LightFilterTimePickerRange,
  LightFilterTimeRange,
  LightFilterTreeSelect,
  LightFilterWeekRange,
  LightFilterYearRange,
  LightWrapper,
  LoginForm,
  LoginFormPage,
  ModalForm,
  QueryFilter,
} from './layouts'
import ProForm from './layouts/ProForm'

Form.install = (app: App) => {
  app.component(Form.name!, Form)
  app.component(MyFormItem.name!, MyFormItem)
}

export const ProFormModule = {
  install(app: App) {
    const list = [
      ProForm,
      BetaSchemaForm,
      ProFormItem,
      ProFormGroup,
      ProFormField,
      ProFormFieldSet,
      ProFormDependency,
      ProFormList,
      ProFormText,
      ProFormTextPassword,
      ProFormTextArea,
      ProFormSelect,
      ProFormDigit,
      ProFormDigitRange,
      ProFormMoney,
      ProFormSwitch,
      ProFormRadio,
      ProFormRadioGroup,
      ProFormRadioButton,
      ProFormCheckbox,
      ProFormCheckboxGroup,
      ProFormCascader,
      ProFormCaptcha,
      ProFormTreeSelect,
      ProFormSlider,
      ProFormRate,
      ProFormSegmented,
      ProFormColorPicker,
      ProFormDatePicker,
      ProFormDateTimePicker,
      ProFormTimePicker,
      ProFormDateRangePicker,
      ProFormDateMonthRangePicker,
      ProFormDateQuarterRangePicker,
      ProFormDateTimeRangePicker,
      ProFormDateWeekRangePicker,
      ProFormDateYearRangePicker,
      ProFormTimeRangePicker,
      ProFormUploadButton,
      ProFormUploadDragger,
      QueryFilter,
      LightFilter,
      LightFilterInput,
      LightFilterPassword,
      LightFilterText,
      LightFilterTextArea,
      LightFilterSelect,
      LightFilterSearchSelect,
      LightFilterTreeSelect,
      LightFilterCascader,
      LightFilterDigit,
      LightFilterDigitRange,
      LightFilterSlider,
      LightFilterDate,
      LightFilterDateTime,
      LightFilterTime,
      LightFilterTimeRange,
      LightFilterDateRange,
      LightFilterDateTimeRange,
      LightFilterWeekRange,
      LightFilterMonthRange,
      LightFilterQuarterRange,
      LightFilterYearRange,
      LightFilterTimePickerRange,
      LightFilterCheckboxGroup,
      LightFilterFieldSet,
      LightFilterSwitch,
      FieldLabel,
      FilterDropdown,
      DrawerForm,
      LoginForm,
      LoginFormPage,
      ModalForm,
    ] as any[]
    list.forEach((c) => {
      if (c?.name) {
        app.component(c.name, c)
      }
    })
  },
}

export {
  BaseForm,
  BetaSchemaForm,
  DrawerForm,
  FieldLabel,
  FilterDropdown,
  Form,
  LightFilter,
  LightFilterCascader,
  LightFilterCheckboxGroup,
  LightFilterDate,
  LightFilterDateRange,
  LightFilterDateTime,
  LightFilterDateTimeRange,
  LightFilterDigit,
  LightFilterDigitRange,
  LightFilterFieldSet,
  LightFilterInput,
  LightFilterMonthRange,
  LightFilterPassword,
  LightFilterQuarterRange,
  LightFilterSearchSelect,
  LightFilterSelect,
  LightFilterSlider,
  LightFilterSwitch,
  LightFilterText,
  LightFilterTextArea,
  LightFilterTime,
  LightFilterTimePickerRange,
  LightFilterTimeRange,
  LightFilterTreeSelect,
  LightFilterWeekRange,
  LightFilterYearRange,
  LightWrapper,
  LoginForm,
  LoginFormPage,
  ModalForm,
  MyFormItem,
  ProForm,
  ProFormCaptcha,
  ProFormCascader,
  ProFormCheckbox,
  ProFormCheckboxGroup,
  ProFormColorPicker,
  ProFormDateMonthRangePicker,
  ProFormDatePicker,
  ProFormDateQuarterRangePicker,
  ProFormDateRangePicker,
  ProFormDateTimePicker,
  ProFormDateTimeRangePicker,
  ProFormDateWeekRangePicker,
  ProFormDateYearRangePicker,
  ProFormDependency,
  ProFormDigit,
  ProFormDigitRange,
  ProFormField,
  ProFormFieldSet,
  ProFormGroup,
  ProFormItem,
  ProFormList,
  ProFormMoney,
  ProFormRadio,
  ProFormRadioButton,
  ProFormRadioGroup,
  ProFormRate,
  ProFormSegmented,
  ProFormSelect,
  ProFormSlider,
  ProFormSwitch,
  ProFormText,
  ProFormTextArea,
  ProFormTextPassword,
  ProFormTimePicker,
  ProFormTimeRangePicker,
  ProFormTreeSelect,
  ProFormUploadButton,
  ProFormUploadDragger,
  QueryFilter,
}

export { PRO_FIELD_SCHEMA_LAYOUT_VALUE_TYPES } from '../field'
export type {
  ProFieldBuiltinValueType,
  ProFieldSchemaLayoutValueType,
  ProFieldValueObjectType,
  ProFieldValueType,
  ProFieldValueTypeInput,
} from '../field'
export type { BetaSchemaFormProps, CaptFieldRef, FormListActionType, ProFormCaptchaProps, ProFormColumnsType, SchemaValueType } from './components'
export { FormListContextKey as FormListContext, provideFormListContext, useFormListContext } from './components/List/FormListContext'
export { FieldContextKey as FieldContext, provideFieldContext, useFieldContext } from './FieldContext'
export { GridContextKey as GridContext, provideGridContext, useGridContext, useGridHelpers } from './helpers'
export type { LightFilterProps, LightWrapperProps, LoginFormPageProps, LoginFormProps, QueryFilterProps, SpanConfig, SpanConfigObject } from './layouts'
export { ProFormContextKey as ProFormContext, provideProFormContext, useProFormContext } from './ProFormContext'
export type {
  ActionButtonProps,
  BaseFormProps,
  CommonFormProps,
  ExtendsProps,
  FieldProps,
  LightFilterFooterRender,
  NamePath,
  ProFormData,
  ProFormDependencyProps,
  ProFormFieldItemProps,
  ProFormFieldProps,
  ProFormFieldPropsFieldProps,
  ProFormFieldSetProps,
  ProFormGridConfig,
  ProFormGroupProps,
  ProFormInstance,
  ProFormItemCreateConfig,
  ProFormItemProps,
  ProFormLayoutType,
  ProFormProps,
  ProFormUploadButtonProps,
  ProFormUploadDraggerProps,
  SearchConfig,
  SearchConvertKeyFn,
  SearchTransformKeyFn,
  SubmitterContext,
  SubmitterProps,
} from './typing'
