import type { App } from 'vue'
import { version } from '../package.json'
import { Button } from './button'
import { FieldModule, ProField, PureProField } from './field'
import { Form, MyFormItem as FormItem, ProFormModule } from './form'
import { ProConfigProvider } from './provider'
import { ProSkeleton } from './skeleton'
import './theme/augmentComponentTokenMap'

export default {
  install(app: App) {
    app.use(Button as any)
    app.use(Form as any)
    app.use(ProSkeleton as any)
    app.use(FieldModule)
    app.use(ProFormModule)
    app.component(ProConfigProvider.name!, ProConfigProvider)
  },
  version,
}

export { Button, Form, FormItem, ProConfigProvider, ProField, ProSkeleton, PureProField, version }
export {
  defaultRenderText,
  FieldCascader,
  FieldCheckbox,
  FieldCode,
  FieldColorPicker,
  FieldDatePicker,
  FieldDigit,
  FieldDigitRange,
  FieldFromNow,
  FieldImage,
  FieldIndexColumn,
  FieldMoney,
  FieldOptions,
  FieldPassword,
  FieldPercent,
  FieldProgress,
  FieldRadio,
  FieldRangePicker,
  FieldRate,
  FieldSecond,
  FieldSegmented,
  FieldSelect,
  FieldSlider,
  FieldStatus,
  FieldSwitch,
  FieldText,
  FieldTextArea,
  FieldTimePicker,
  FieldTimeRangePicker,
  FieldTreeSelect,
  ProFieldBadgeColor,
} from './field'

export type {
  FieldCascaderProps,
  FieldDigitRangeProps,
  FieldMoneyProps,
  FieldSelectProps,
  FieldTreeSelectProps,
  ProConfigContextType,
  ProFieldEmptyText,
  ProFieldFCRenderProps,
  ProFieldPropsType,
  ProFieldRenderProps,
  ProFieldTextType,
  ProFieldValueType,
  ProFieldValueTypeInput,
  ProRenderFieldPropsType,
} from './field'
export {
  BaseForm,
  BetaSchemaForm,
  FieldContext,
  FieldLabel,
  FilterDropdown,
  FormListContext,
  GridContext,
  LightFilter,
  LightFilterCascader,
  LightFilterCheckboxGroup,
  LightFilterDate,
  LightFilterDateRange,
  LightFilterDateTime,
  LightFilterDateTimeRange,
  LightFilterDigit,
  LightFilterDigitRange,
  LightFilterFieldSet,
  LightFilterInput,
  LightFilterMonthRange,
  LightFilterPassword,
  LightFilterQuarterRange,
  LightFilterSearchSelect,
  LightFilterSelect,
  LightFilterSlider,
  LightFilterSwitch,
  LightFilterText,
  LightFilterTextArea,
  LightFilterTime,
  LightFilterTimePickerRange,
  LightFilterTimeRange,
  LightFilterTreeSelect,
  LightFilterWeekRange,
  LightFilterYearRange,
  LightWrapper,
  LoginForm,
  LoginFormPage,
  PRO_FIELD_SCHEMA_LAYOUT_VALUE_TYPES,
  ProForm,
  ProFormCascader,
  ProFormCheckbox,
  ProFormCheckboxGroup,
  ProFormColorPicker,
  ProFormContext,
  ProFormDateMonthRangePicker,
  ProFormDatePicker,
  ProFormDateQuarterRangePicker,
  ProFormDateRangePicker,
  ProFormDateTimePicker,
  ProFormDateTimeRangePicker,
  ProFormDateWeekRangePicker,
  ProFormDateYearRangePicker,
  ProFormDependency,
  ProFormDigit,
  ProFormDigitRange,
  ProFormField,
  ProFormFieldSet,
  ProFormGroup,
  ProFormItem,
  ProFormList,
  ProFormModule,
  ProFormMoney,
  ProFormRadio,
  ProFormRadioButton,
  ProFormRadioGroup,
  ProFormRate,
  ProFormSegmented,
  ProFormSelect,
  ProFormSlider,
  ProFormSwitch,
  ProFormText,
  ProFormTextArea,
  ProFormTextPassword,
  ProFormTimePicker,
  ProFormTimeRangePicker,
  ProFormTreeSelect,
  ProFormUploadButton,
  ProFormUploadDragger,
  provideFieldContext,
  provideFormListContext,
  provideGridContext,
  provideProFormContext,
  QueryFilter,
  useFieldContext,
  useFormListContext,
  useGridContext,
  useGridHelpers,
  useProFormContext,
} from './form'

export type {
  BaseFormProps,
  BetaSchemaFormProps,
  CommonFormProps,
  FormListActionType,
  LightFilterProps,
  LightWrapperProps,
  LoginFormPageProps,
  LoginFormProps,
  NamePath,
  ProFormColumnsType,
  ProFormData,
  ProFormFieldItemProps,
  ProFormFieldSetProps,
  ProFormGridConfig,
  ProFormGroupProps,
  ProFormItemCreateConfig,
  ProFormItemProps,
  ProFormLayoutType,
  ProFormProps,
  ProFormUploadButtonProps,
  ProFormUploadDraggerProps,
  QueryFilterProps,
  SchemaValueType,
  SpanConfig,
  SpanConfigObject,
  SubmitterProps,
} from './form'
export {
  arEGIntl,
  caESIntl,
  ConfigConsumer,
  createIntl,
  csCZIntl,
  deDEIntl,
  enGBIntl,
  enUSIntl,
  esESIntl,
  faIRIntl,
  findIntlKeyByAntdLocaleKey,
  frFRIntl,
  heILIntl,
  hrHRIntl,
  idIDIntl,
  intlMap,
  intlMapKeys,
  isNeedOpenHash,
  itITIntl,
  jaJPIntl,
  koKRIntl,
  lighten,
  mnMNIntl,
  msMYIntl,
  nlNLIntl,
  operationUnit,
  plPLIntl,
  ProProvider,
  proTheme,
  ptBRIntl,
  resetComponent,
  roROIntl,
  ruRUIntl,
  setAlpha,
  skSKIntl,
  srRSIntl,
  svSEIntl,
  thTHIntl,
  trTRIntl,
  ukUAIntl,
  useIntl,
  useProProviderContext,
  useStyle,
  uzUZIntl,
  viVNIntl,
  zhCNIntl,
  zhHKIntl,
  zhTWIntl,
} from './provider'
export type {
  BaseProFieldFC,
  ConfigContextPropsType,
  DeepPartial,
  IntlType,
  ParamsType,
  ProAliasToken,
  ProFieldFCMode,
  ProSchemaValueEnumMap,
  ProSchemaValueEnumObj,
  ProTokenType,
  ProFieldFCRenderProps as ProviderProFieldFCRenderProps,
  ProRenderFieldPropsType as ProviderProRenderFieldPropsType,
} from './provider'
export { DescriptionsPageSkeleton, DescriptionsSkeleton, TableItemSkeleton, TableSkeleton } from './skeleton'
export { ListPageSkeleton, ListSkeleton, ListSkeletonItem, ListToolbarSkeleton, PageHeaderSkeleton } from './skeleton'
export { ResultPageSkeleton } from './skeleton'
export {
  genProComponentStyleHook,
  genProStyleHooks,
  genProSubStyleComponent,
} from './theme/genProStyleUtils'
