import type { App } from 'vue'
import { version } from '../package.json'
import { CardModule, CheckCard, ProCard, Statistic, StatisticCard } from './card'
import { DescriptionsModule, ProDescriptions } from './descriptions'
import { FieldModule, ProField, PureProField } from './field'
import { FormModule, ProForm } from './form'
import { LayoutModule, ProLayout } from './layout'
import { BaseProList, ListModule, ProList } from './list'
import { ProConfigProvider } from './provider'
import { ProSkeleton } from './skeleton'
import { DragSortTable, EditableProTable, ListToolBar, ProTable, Search, TableDropdown, TableModule } from './table'
import './theme/augmentComponentTokenMap'

export default {
  install(app: App) {
    app.use(ProSkeleton as any)
    app.use(FieldModule)
    app.use(FormModule)
    app.use(CardModule)
    app.use(DescriptionsModule)
    app.use(LayoutModule)
    app.use(TableModule)
    app.use(ListModule)
    app.component(ProConfigProvider.name!, ProConfigProvider)
  },
  version,
}

export { BaseProList, CheckCard, DescriptionsModule, DragSortTable, EditableProTable, FormModule, LayoutModule, ListModule, ListToolBar, ProCard, ProConfigProvider, ProDescriptions, ProField, ProForm, ProLayout, ProList, ProSkeleton, ProTable, PureProField, Search, Statistic, StatisticCard, TableDropdown, version }
export { CardModule } from './card'
export type {
  CheckCardGroupProps,
  CheckCardProps,
  ProCardProps,
  ProCardTabsProps,
  StatisticCardProps,
  StatisticProps,
} from './card'
export type {
  DescriptionsItemProps,
  RowEditableConfig as DescriptionsRowEditableConfig,
  ProDescriptionsActionType,
  ProDescriptionsColumn,
  ProDescriptionsItemProps,
  ProDescriptionsProps,
  ProDescriptionsRequestResult,
  RequestData,
} from './descriptions'
export {
  defaultRenderText,
  FieldCascader,
  FieldCheckbox,
  FieldCode,
  FieldColorPicker,
  FieldDatePicker,
  FieldDigit,
  FieldDigitRange,
  FieldFromNow,
  FieldImage,
  FieldIndexColumn,
  FieldMoney,
  FieldOptions,
  FieldPassword,
  FieldPercent,
  FieldProgress,
  FieldRadio,
  FieldRangePicker,
  FieldRate,
  FieldSecond,
  FieldSegmented,
  FieldSelect,
  FieldSlider,
  FieldStatus,
  FieldSwitch,
  FieldText,
  FieldTextArea,
  FieldTimePicker,
  FieldTimeRangePicker,
  FieldTreeSelect,
  ProFieldBadgeColor,
  proFieldParsingValueEnumToArray,
} from './field'

export type {
  FieldCascaderExpose,
  FieldCascaderProps,
  FieldCheckboxExpose,
  FieldColorPickerExpose,
  FieldCodeExpose,
  FieldDatePickerExpose,
  FieldDigitExpose,
  FieldDigitRangeExpose,
  FieldDigitRangeProps,
  FieldFromNowExpose,
  FieldImageExpose,
  FieldIndexColumnExpose,
  FieldMoneyExpose,
  FieldMoneyProps,
  FieldPasswordExpose,
  FieldPercentExpose,
  FieldProgressExpose,
  FieldRateExpose,
  FieldRadioExpose,
  FieldRangePickerExpose,
  FieldSecondExpose,
  FieldSelectExpose,
  FieldSelectProps,
  FieldSegmentedExpose,
  FieldSliderExpose,
  FieldSwitchExpose,
  FieldTimePickerExpose,
  FieldTimeRangePickerExpose,
  FieldTextExpose,
  FieldTextAreaExpose,
  FieldTreeSelectExpose,
  FieldTreeSelectProps,
  ProConfigContextType,
  ProFieldEmptyText,
  ProFieldFCRenderProps,
  ProFieldMoneyProps,
  ProFieldPropsType,
  ProFieldRenderProps,
  ProFieldTextType,
  ProFieldValueType,
  ProFieldValueTypeInput,
  ProRenderFieldPropsType,
} from './field'
export {
  BetaSchemaForm,
  DrawerForm,
  FieldContext,
  FormListContext,
  LightFilter,
  LightWrapper,
  LoginForm,
  LoginFormPage,
  ModalForm,
  ProFormCaptcha,
  ProFormCascader,
  ProFormCheckbox,
  ProFormCheckboxGroup,
  ProFormColorPicker,
  ProFormDateMonthPicker,
  ProFormDateMonthRangePicker,
  ProFormDatePicker,
  ProFormDateQuarterPicker,
  ProFormDateQuarterRangePicker,
  ProFormDateRangePicker,
  ProFormDateTimePicker,
  ProFormDateTimeRangePicker,
  ProFormDateWeekPicker,
  ProFormDateWeekRangePicker,
  ProFormDateYearPicker,
  ProFormDateYearRangePicker,
  ProFormDependency,
  ProFormDigit,
  ProFormDigitRange,
  ProFormField,
  ProFormFieldSet,
  ProFormGroup,
  ProFormItem,
  ProFormItemRender,
  ProFormList,
  ProFormMoney,
  ProFormRadio,
  ProFormRadioGroup,
  ProFormRate,
  ProFormSegmented,
  ProFormSelect,
  ProFormSlider,
  ProFormSwitch,
  ProFormText,
  ProFormTextArea,
  ProFormTimePicker,
  ProFormTimeRangePicker,
  ProFormTreeSelect,
  ProFormUploadButton,
  ProFormUploadDragger,
  QueryFilter,
  StepForm,
  StepsForm,
} from './form'
export type {
  FormListActionType,
  GroupProps,
  LightFilterFooterRender,
  LightWrapperProps,
  ProFormCaptchaProps,
  ProFormCheckboxGroupProps,
  ProFormCheckboxProps,
  ProFormColorPickerProps,
  ProFormColumnsType,
  ProFormDependencyProps,
  ProFormDigitProps,
  ProFormDigitRangeProps,
  ProFormFieldItemProps,
  ProFormFieldProps,
  ProFormFieldSetProps,
  ProFormInstance,
  ProFormItemProps,
  ProFormLayoutType,
  ProFormListProps,
  ProFormMoneyProps,
  ProFormProps,
  ProFormRadioGroupProps,
  ProFormSelectProps,
  ProFormSliderProps,
  ProFormSwitchProps,
  ProFormTreeSelectProps,
  ProFormUploadButtonProps,
  ProFormUploadDraggerProps,
} from './form'
export {
  BaseMenu,
  DefaultFooter,
  DefaultHeader,
  FooterToolbar,
  getMenuData,
  getPageTitle,
  GridContent,
  PageContainer,
  PageHeader,
  PageLoading,
  ProBreadcrumb,
  ProPageHeader,
  RouteContext,
  RouteContextProvider,
  SiderMenu,
  TopNavHeader,
  useRouteContext,
} from './layout'
export type {
  AppItemProps,
  AppListProps,
  BaseMenuProps,
  FooterProps,
  HeaderProps,
  MenuDataItem,
  MenuMode,
  PageContainerProps,
  PageHeaderProps,
  ProLayoutLayoutMode,
  ProLayoutMenuRenderCallbackProps,
  ProLayoutNavMenuSelectInfo,
  ProLayoutProps,
  ProSettings,
  RouterTypes,
  Settings,
  SiderMenuProps,
} from './layout'
export type {
  BaseProListMetas,
  GetComponentProps,
  ProListItemRender,
  Key as ProListKey,
  ProListMeta,
  ProListMetas,
  ProListProps,
  TriggerEventHandler,
} from './list'
export {
  arEGIntl,
  caESIntl,
  ConfigConsumer,
  createIntl,
  csCZIntl,
  deDEIntl,
  enGBIntl,
  enUSIntl,
  esESIntl,
  faIRIntl,
  findIntlKeyByAntdLocaleKey,
  frFRIntl,
  heILIntl,
  hrHRIntl,
  idIDIntl,
  intlMap,
  intlMapKeys,
  isNeedOpenHash,
  itITIntl,
  jaJPIntl,
  koKRIntl,
  lighten,
  mnMNIntl,
  msMYIntl,
  nlNLIntl,
  operationUnit,
  plPLIntl,
  ProProvider,
  proTheme,
  ptBRIntl,
  resetComponent,
  roROIntl,
  ruRUIntl,
  setAlpha,
  skSKIntl,
  srRSIntl,
  svSEIntl,
  thTHIntl,
  trTRIntl,
  ukUAIntl,
  useIntl,
  useProProviderContext,
  useStyle,
  uzUZIntl,
  viVNIntl,
  zhCNIntl,
  zhHKIntl,
  zhTWIntl,
} from './provider'
export type {
  BaseProFieldFC,
  ConfigContextPropsType,
  DeepPartial,
  IntlType,
  ParamsType,
  ProAliasToken,
  ProFieldFCMode,
  ProSchemaValueEnumMap,
  ProSchemaValueEnumObj,
  ProSchemaValueEnumType,
  ProTokenType,
  ProFieldFCRenderProps as ProviderProFieldFCRenderProps,
  ProRenderFieldPropsType as ProviderProRenderFieldPropsType,
} from './provider'
export { DescriptionsSkeleton, TableItemSkeleton, TableSkeleton } from './skeleton'
export { ListPageSkeleton, ListSkeleton, ListSkeletonItem, ListToolbarSkeleton, PageHeaderSkeleton } from './skeleton'
export { TableModule } from './table'
export type {
  ActionType,
  ColumnsState,
  DragTableProps,
  EditableFormInstance,
  EditableProTableProps,
  ProColumns,
  ProColumnType,
  ProTableProps,
  RequestData as ProTableRequestData,
  RowEditableConfig,
} from './table'
export {
  genProComponentStyleHook,
  genProStyleHooks,
  genProSubStyleComponent,
} from './theme/genProStyleUtils'
