/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('antdv-next')['Alert']
    AAnchor: typeof import('antdv-next')['Anchor']
    AApp: typeof import('antdv-next')['App']
    AButton: typeof import('antdv-next')['Button']
    ACard: typeof import('antdv-next')['Card']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    AFlex: typeof import('antdv-next')['Flex']
    AForm: typeof import('antdv-next')['Form']
    AFormItem: typeof import('antdv-next')['FormItem']
    AInput: typeof import('antdv-next')['Input']
    AInputGroup: typeof import('antdv-next')['InputGroup']
    AInputNumber: typeof import('antdv-next')['InputNumber']
    AModal: typeof import('antdv-next')['Modal']
    ASelect: typeof import('antdv-next')['Select']
    ASelectOption: typeof import('antdv-next')['SelectOption']
    ASkeleton: typeof import('antdv-next')['Skeleton']
    ASpace: typeof import('antdv-next')['Space']
    ASpaceCompact: typeof import('antdv-next')['SpaceCompact']
    ASwitch: typeof import('antdv-next')['Switch']
    ATable: typeof import('antdv-next')['Table']
    ATabPane: typeof import('antdv-next')['TabPane']
    ATabs: typeof import('antdv-next')['Tabs']
    ATag: typeof import('antdv-next')['Tag']
    ATooltip: typeof import('antdv-next')['Tooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AAlert: typeof import('antdv-next')['Alert']
  const AAnchor: typeof import('antdv-next')['Anchor']
  const AApp: typeof import('antdv-next')['App']
  const AButton: typeof import('antdv-next')['Button']
  const ACard: typeof import('antdv-next')['Card']
  const AConfigProvider: typeof import('antdv-next')['ConfigProvider']
  const AFlex: typeof import('antdv-next')['Flex']
  const AForm: typeof import('antdv-next')['Form']
  const AFormItem: typeof import('antdv-next')['FormItem']
  const AInput: typeof import('antdv-next')['Input']
  const AInputGroup: typeof import('antdv-next')['InputGroup']
  const AInputNumber: typeof import('antdv-next')['InputNumber']
  const AModal: typeof import('antdv-next')['Modal']
  const ASelect: typeof import('antdv-next')['Select']
  const ASelectOption: typeof import('antdv-next')['SelectOption']
  const ASkeleton: typeof import('antdv-next')['Skeleton']
  const ASpace: typeof import('antdv-next')['Space']
  const ASpaceCompact: typeof import('antdv-next')['SpaceCompact']
  const ASwitch: typeof import('antdv-next')['Switch']
  const ATable: typeof import('antdv-next')['Table']
  const ATabPane: typeof import('antdv-next')['TabPane']
  const ATabs: typeof import('antdv-next')['Tabs']
  const ATag: typeof import('antdv-next')['Tag']
  const ATooltip: typeof import('antdv-next')['Tooltip']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}