/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAnchor: typeof import('antdv-next')['Anchor']
    AApp: typeof import('antdv-next')['App']
    AButton: typeof import('antdv-next')['Button']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    AFlex: typeof import('antdv-next')['Flex']
    AInput: typeof import('antdv-next')['Input']
    AInputNumber: typeof import('antdv-next')['InputNumber']
    ASkeleton: typeof import('antdv-next')['Skeleton']
    ATabPane: typeof import('antdv-next')['TabPane']
    ATabs: typeof import('antdv-next')['Tabs']
    ATag: typeof import('antdv-next')['Tag']
    ATooltip: typeof import('antdv-next')['Tooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AAnchor: typeof import('antdv-next')['Anchor']
  const AApp: typeof import('antdv-next')['App']
  const AButton: typeof import('antdv-next')['Button']
  const AConfigProvider: typeof import('antdv-next')['ConfigProvider']
  const AFlex: typeof import('antdv-next')['Flex']
  const AInput: typeof import('antdv-next')['Input']
  const AInputNumber: typeof import('antdv-next')['InputNumber']
  const ASkeleton: typeof import('antdv-next')['Skeleton']
  const ATabPane: typeof import('antdv-next')['TabPane']
  const ATabs: typeof import('antdv-next')['Tabs']
  const ATag: typeof import('antdv-next')['Tag']
  const ATooltip: typeof import('antdv-next')['Tooltip']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}