/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AFlex: typeof import('antdv-next')['Flex']
    ASkeleton: typeof import('antdv-next')['Skeleton']
    ATabPane: typeof import('antdv-next')['TabPane']
    ATabs: typeof import('antdv-next')['Tabs']
    ATooltip: typeof import('antdv-next')['Tooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AFlex: typeof import('antdv-next')['Flex']
  const ASkeleton: typeof import('antdv-next')['Skeleton']
  const ATabPane: typeof import('antdv-next')['TabPane']
  const ATabs: typeof import('antdv-next')['Tabs']
  const ATooltip: typeof import('antdv-next')['Tooltip']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}